.\" A sample man page. 
.\" Contact admin@yourcompany.com to correct errors or omissions. 
.TH logsplit 1 "04 October 2006" "0.99" "logsplit"
.SH NAME
logsplit \- Used for splitting httpd logs
.SH SYNOPSIS
.\"
.B logsplit 
[OPTIONS]... LOGDIR 
. 

.SH OPTIONS

.IP "-b, --burst_write_interval <SECONDS>"
Interval between burst writing, default 1 second

.IP "-r, --rotate_enable"
Enable logrotating by logsplit

.IP "-i, --rotate_interval <SECONDS>"
Interval between the log directory is checked on oversized files

.IP "-m, --max_logfile_size <BYTES>"
If a logfile exceeds the number of bytes given the log file will be rotated if the option --rotate_enable or -r is set

.IP "-o, --hook_dir <DIR>"
Executes all scripts with fileops 700 and 500 before the files are rotated, while the hooks get executed the new logs are written to an temporary file

.IP "-s, --statdir <DIR>"
Directory to write daily bandwidth usage, every month will get his own file named: YYYYMM.bandwidth.log, The data format will be xml.

.IP "-h, --help"
Display quick help


.SH DESCRIPTION
.B logsplit
is a burst writer behind the apache or apache2 webserver or to use as a tool to split logs. beside this jobs daily statistics are made up and written to disk per month and rotates the splitted output. You can hook scripts with the given hook directory to execute scripts on a pre-rotate event from logsplit

.SH EXAMPLE
Add the folowing two line to your /etc/httpd/conf/httpd.conf 

LogFormat "%v %h %l %u %t \\"%r\\" %>s %b \\"%{Referer}i" \\"%{User-Agent}i\\"\\" spcombined

CustomLog "|/usr/local/bin/logsplit -b 10 -r -i 180 -m 50000 -s ./somestatdir ./somelogdir" spcombined


Commandlines example:
./logsplit -b 10 -r -i 180 -m 50000 -s ./somestatdir ./somelogdir < some.log

.SH FILES
.P 
.I /usr/local/bin/logsplit
.SH SEE ALSO
.BR apache (1) 
.SH BUGS
No known bugs at this time. 
.SH AUTHOR
.nf
W.A. van der Meeren (danny@openpanel.com)
.fi
.SH HISTORY
2006 \- The logsplit is introduced by Openpanel